var f,tem;
f = file_bin_open("save"+string(global.savenum),1);
tem = room;
file_bin_write_byte(f,floor(tem/10000));
tem -= floor(tem/10000)*10000;
file_bin_write_byte(f,floor(tem/100));
tem -= floor(tem/100)*100;
file_bin_write_byte(f,tem);
tem = player.x;
file_bin_write_byte(f,floor(tem/10000));
tem -= floor(tem/10000)*10000;
file_bin_write_byte(f,floor(tem/100));
tem -= floor(tem/100)*100;
file_bin_write_byte(f,tem);
tem = player.y;
file_bin_write_byte(f,floor(tem/10000));
tem -= floor(tem/10000)*10000;
file_bin_write_byte(f,floor(tem/100));
tem -= floor(tem/100)*100;
file_bin_write_byte(f,tem);
file_bin_write_byte(f,global.difficulty);
file_bin_write_byte(f,global.item1);
file_bin_write_byte(f,global.item2);
file_bin_write_byte(f,global.item3);
file_bin_write_byte(f,global.item4);
file_bin_write_byte(f,global.item5);
file_bin_write_byte(f,global.item6);
file_bin_write_byte(f,global.item7);
file_bin_write_byte(f,global.item8);
file_bin_write_byte(f,global.item9);
file_bin_write_byte(f,global.item10);
file_bin_close(f);
saveDeathTime();
